# Generated by Django 5.0.6 on 2024-05-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=72, verbose_name="Ім'я автора")),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Автори",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Назва книги")),
                ("publication_year", models.IntegerField(verbose_name="Рік видання")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="book_catalogue.author",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="books",
            field=models.ManyToManyField(
                related_name="authors", to="book_catalogue.book", verbose_name="Книги"
            ),
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=72, verbose_name="Назва видавництва"),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="book_publisher",
                        to="book_catalogue.book",
                        verbose_name="Книги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видавець",
                "verbose_name_plural": "Видавці",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book_catalogue.publisher",
            ),
        ),
    ]
