# Generated by Django 5.0.6 on 2024-05-10 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="books",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="authors",
                to="book_catalogue.book",
                verbose_name="Книги",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book_catalogue.publisher",
                verbose_name="Видавець",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="author",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="book_publisher",
                to="book_catalogue.book",
                verbose_name="Книги",
            ),
        ),
    ]
