# Generated by Django 5.0.6 on 2024-05-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_catalogue", "0002_alter_author_books_alter_book_publisher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(
                default="Не надано", max_length=72, verbose_name="Країна"
            ),
            preserve_default=False,
        ),
    ]
