# Generated by Django 5.0.6 on 2024-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_catalogue", "0003_author_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="books",
            field=models.ManyToManyField(
                blank=True,
                related_name="authors",
                to="book_catalogue.book",
                verbose_name="Книги",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="author",
            field=models.ManyToManyField(
                blank=True,
                related_name="book_publisher",
                to="book_catalogue.book",
                verbose_name="Книги",
            ),
        ),
    ]
