# Generated by Django 5.0.6 on 2024-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_catalogue", "0004_alter_author_books_alter_publisher_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country_en",
            field=models.CharField(max_length=72, null=True, verbose_name="Країна"),
        ),
        migrations.AddField(
            model_name="author",
            name="country_uk",
            field=models.CharField(max_length=72, null=True, verbose_name="Країна"),
        ),
        migrations.AddField(
            model_name="author",
            name="name_en",
            field=models.CharField(
                max_length=72, null=True, verbose_name="Ім'я автора"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="name_uk",
            field=models.CharField(
                max_length=72, null=True, verbose_name="Ім'я автора"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="title_en",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Назва книги"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="title_uk",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Назва книги"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="name_en",
            field=models.CharField(
                max_length=72, null=True, verbose_name="Назва видавництва"
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="name_uk",
            field=models.CharField(
                max_length=72, null=True, verbose_name="Назва видавництва"
            ),
        ),
    ]
